//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegularExpressionsCalculator.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegularExpressionsCalculator.App_Data.Keywords", typeof(Keywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after replacement, after.
        /// </summary>
        internal static string AfterReplace {
            get {
                return ResourceManager.GetString("AfterReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least x times, at least.
        /// </summary>
        internal static string AtLeast {
            get {
                return ResourceManager.GetString("AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before replacement, before.
        /// </summary>
        internal static string BeforeReplace {
            get {
                return ResourceManager.GetString("BeforeReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literally, begin literal, interpret literally, literal.
        /// </summary>
        internal static string BeginLiteral {
            get {
                return ResourceManager.GetString("BeginLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boundary, word end.
        /// </summary>
        internal static string BoundaryAnchor {
            get {
                return ResourceManager.GetString("BoundaryAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x or y or z, any of the following.
        /// </summary>
        internal static string BracketRange {
            get {
                return ResourceManager.GetString("BracketRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beginning of word, beginning of line, begin.
        /// </summary>
        internal static string CaretAnchor {
            get {
                return ResourceManager.GetString("CaretAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to control, control character.
        /// </summary>
        internal static string ControlChar {
            get {
                return ResourceManager.GetString("ControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digit, digits, digit characters.
        /// </summary>
        internal static string DigitChar {
            get {
                return ResourceManager.GetString("DigitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digit range, any of the following digits.
        /// </summary>
        internal static string DigitRange {
            get {
                return ResourceManager.GetString("DigitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end, end of word, end of line.
        /// </summary>
        internal static string DollarAnchor {
            get {
                return ResourceManager.GetString("DollarAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literally, end literal, interpret literally literal.
        /// </summary>
        internal static string EndLiteral {
            get {
                return ResourceManager.GetString("EndLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace whole, entire replacement, replace all.
        /// </summary>
        internal static string EntireReplacement {
            get {
                return ResourceManager.GetString("EntireReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match exactly x times, match exact x, exactly x.
        /// </summary>
        internal static string Exact {
            get {
                return ResourceManager.GetString("Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed character, feed.
        /// </summary>
        internal static string FeedChar {
            get {
                return ResourceManager.GetString("FeedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first replacement, replace first.
        /// </summary>
        internal static string FirstReplacement {
            get {
                return ResourceManager.GetString("FirstReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global, search globally.
        /// </summary>
        internal static string GlobalPattern {
            get {
                return ResourceManager.GetString("GlobalPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greedy one, greedy match one or more, one or more, 1 or more.
        /// </summary>
        internal static string GreedyOne {
            get {
                return ResourceManager.GetString("GreedyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greedy zero, greedy match zero or more, zero or more, 0 or more.
        /// </summary>
        internal static string GreedyZero {
            get {
                return ResourceManager.GetString("GreedyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anything in the following group, group range x, range x.
        /// </summary>
        internal static string GroupRange {
            get {
                return ResourceManager.GetString("GroupRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hexadecimal characters, hex char, hex string char, hex string.
        /// </summary>
        internal static string HexStrChar {
            get {
                return ResourceManager.GetString("HexStrChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if x then y, if x else y, if x do y.
        /// </summary>
        internal static string IfThen {
            get {
                return ResourceManager.GetString("IfThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if x then y else z, if x else y finally z, if x do y else z.
        /// </summary>
        internal static string IfThenElse {
            get {
                return ResourceManager.GetString("IfThenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last replacement.
        /// </summary>
        internal static string LastReplacement {
            get {
                return ResourceManager.GetString("LastReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lazy, lazy match, lazily, lazily match.
        /// </summary>
        internal static string Lazy {
            get {
                return ResourceManager.GetString("Lazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to literal, literally.
        /// </summary>
        internal static string Literal {
            get {
                return ResourceManager.GetString("Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look ahead, lookahead, search before match.
        /// </summary>
        internal static string Lookahead {
            get {
                return ResourceManager.GetString("Lookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to look behind, lookbehind, search after match.
        /// </summary>
        internal static string Lookbehind {
            get {
                return ResourceManager.GetString("Lookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negative look ahead, negative lookahead, neg lookahead, neg look ahead.
        /// </summary>
        internal static string NegLookahead {
            get {
                return ResourceManager.GetString("NegLookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negative look behind, negative lookbehind, neg lookbehind, neg look behind.
        /// </summary>
        internal static string NegLookbehind {
            get {
                return ResourceManager.GetString("NegLookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new line, newline.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non digit, non-digit, not digit.
        /// </summary>
        internal static string NonDigit {
            get {
                return ResourceManager.GetString("NonDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non or range x, not x or y or z .
        /// </summary>
        internal static string NonOrRange {
            get {
                return ResourceManager.GetString("NonOrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non range x, nonrange x, not x .
        /// </summary>
        internal static string NonRange {
            get {
                return ResourceManager.GetString("NonRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-word, nonword, non word, not words, not word character, non word char.
        /// </summary>
        internal static string NonWord {
            get {
                return ResourceManager.GetString("NonWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not space, nonspace.
        /// </summary>
        internal static string NotSpace {
            get {
                return ResourceManager.GetString("NotSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not word boundary, non-word boundary.
        /// </summary>
        internal static string NotWordBoundary {
            get {
                return ResourceManager.GetString("NotWordBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nth replacement, nth replace, replace nth, x replacement.
        /// </summary>
        internal static string NthReplacement {
            get {
                return ResourceManager.GetString("NthReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octalchar x, octal character x, octal char x.
        /// </summary>
        internal static string OctalChar {
            get {
                return ResourceManager.GetString("OctalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octalstr x, octalstring x, octal string x.
        /// </summary>
        internal static string OctalStr {
            get {
                return ResourceManager.GetString("OctalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onceonly, once only, match only once.
        /// </summary>
        internal static string OnceOnly {
            get {
                return ResourceManager.GetString("OnceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or, x or y or z, any of the following x.
        /// </summary>
        internal static string OrBracket {
            get {
                return ResourceManager.GetString("OrBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or, x or y.
        /// </summary>
        internal static string OrRange {
            get {
                return ResourceManager.GetString("OrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passiverange, passive match, passive x.
        /// </summary>
        internal static string PassiveRange {
            get {
                return ResourceManager.GetString("PassiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to match any character, match any char, match any x.
        /// </summary>
        internal static string PeriodRange {
            get {
                return ResourceManager.GetString("PeriodRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least x to y, at least x and no more than y, match x to y, match x-y.
        /// </summary>
        internal static string RangeQuant {
            get {
                return ResourceManager.GetString("RangeQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return, returnchar, returncharacter, return character, return char.
        /// </summary>
        internal static string ReturnChar {
            get {
                return ResourceManager.GetString("ReturnChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second replacement, second replace, 2nd replace.
        /// </summary>
        internal static string SecondReplacement {
            get {
                return ResourceManager.GetString("SecondReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space, spacechar, spacecharacter, space char, space character.
        /// </summary>
        internal static string SpaceChar {
            get {
                return ResourceManager.GetString("SpaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin string, string begin, strbegin, beginning of string.
        /// </summary>
        internal static string StringBegin {
            get {
                return ResourceManager.GetString("StringBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end string, string end, strend, end of string.
        /// </summary>
        internal static string StringEnd {
            get {
                return ResourceManager.GetString("StringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subpattern num x, subpattern x, sub num x.
        /// </summary>
        internal static string SubpatternNum {
            get {
                return ResourceManager.GetString("SubpatternNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subpattern range x, sub range x.
        /// </summary>
        internal static string SubPatternRange {
            get {
                return ResourceManager.GetString("SubPatternRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab, tabchar, tabcharacter, tab char, tab character.
        /// </summary>
        internal static string TabChar {
            get {
                return ResourceManager.GetString("TabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verttab, vert tab, verttabchar, vertchar.
        /// </summary>
        internal static string VertTabChar {
            get {
                return ResourceManager.GetString("VertTabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to word x, wordchar x.
        /// </summary>
        internal static string WordChar {
            get {
                return ResourceManager.GetString("WordChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wordend, word end, end of word.
        /// </summary>
        internal static string WordEnd {
            get {
                return ResourceManager.GetString("WordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wordstart, word start, start of word.
        /// </summary>
        internal static string WordStart {
            get {
                return ResourceManager.GetString("WordStart", resourceCulture);
            }
        }
    }
}
