//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegularExpressionsCalculator.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegexSymbols {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegexSymbols() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegularExpressionsCalculator.App_Data.RegexSymbols", typeof(RegexSymbols).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&apos; or \&apos;.
        /// </summary>
        internal static string AfterReplace {
            get {
                return ResourceManager.GetString("AfterReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchors.
        /// </summary>
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertions.
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5, }.
        /// </summary>
        internal static string AtLeast {
            get {
                return ResourceManager.GetString("AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $` or \`.
        /// </summary>
        internal static string BeforeReplace {
            get {
                return ResourceManager.GetString("BeforeReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Q.
        /// </summary>
        internal static string BeginLiteral {
            get {
                return ResourceManager.GetString("BeginLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b.
        /// </summary>
        internal static string BoundaryAnchor {
            get {
                return ResourceManager.GetString("BoundaryAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [abc].
        /// </summary>
        internal static string BracketRange {
            get {
                return ResourceManager.GetString("BracketRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string CaretAnchor {
            get {
                return ResourceManager.GetString("CaretAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Classes.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?#.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \c.
        /// </summary>
        internal static string ControlChar {
            get {
                return ResourceManager.GetString("ControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d.
        /// </summary>
        internal static string DigitChar {
            get {
                return ResourceManager.GetString("DigitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0-6].
        /// </summary>
        internal static string DigitRange {
            get {
                return ResourceManager.GetString("DigitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string DollarAnchor {
            get {
                return ResourceManager.GetString("DollarAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \E.
        /// </summary>
        internal static string EndLiteral {
            get {
                return ResourceManager.GetString("EndLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&amp; or \&amp;.
        /// </summary>
        internal static string EntireReplacement {
            get {
                return ResourceManager.GetString("EntireReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape Characters.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5}.
        /// </summary>
        internal static string Exact {
            get {
                return ResourceManager.GetString("Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f.
        /// </summary>
        internal static string FeedChar {
            get {
                return ResourceManager.GetString("FeedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1 or \1.
        /// </summary>
        internal static string FirstReplacement {
            get {
                return ResourceManager.GetString("FirstReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \g.
        /// </summary>
        internal static string GlobalPattern {
            get {
                return ResourceManager.GetString("GlobalPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string GreedyOne {
            get {
                return ResourceManager.GetString("GreedyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string GreedyZero {
            get {
                return ResourceManager.GetString("GreedyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and Ranges.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (...).
        /// </summary>
        internal static string GroupRange {
            get {
                return ResourceManager.GetString("GroupRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \xhh.
        /// </summary>
        internal static string HexStrChar {
            get {
                return ResourceManager.GetString("HexStrChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?().
        /// </summary>
        internal static string IfThen {
            get {
                return ResourceManager.GetString("IfThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?()|.
        /// </summary>
        internal static string IfThenElse {
            get {
                return ResourceManager.GetString("IfThenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $+ or \+.
        /// </summary>
        internal static string LastReplacement {
            get {
                return ResourceManager.GetString("LastReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Lazy {
            get {
                return ResourceManager.GetString("Lazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string Literal {
            get {
                return ResourceManager.GetString("Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?=.
        /// </summary>
        internal static string Lookahead {
            get {
                return ResourceManager.GetString("Lookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?&lt;=.
        /// </summary>
        internal static string Lookbehind {
            get {
                return ResourceManager.GetString("Lookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Modifiers.
        /// </summary>
        internal static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?!.
        /// </summary>
        internal static string NegLookahead {
            get {
                return ResourceManager.GetString("NegLookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?!= or ?&lt;!.
        /// </summary>
        internal static string NegLookbehind {
            get {
                return ResourceManager.GetString("NegLookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        internal static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \D.
        /// </summary>
        internal static string NonDigit {
            get {
                return ResourceManager.GetString("NonDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^abc].
        /// </summary>
        internal static string NonOrRange {
            get {
                return ResourceManager.GetString("NonOrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^a-q].
        /// </summary>
        internal static string NonRange {
            get {
                return ResourceManager.GetString("NonRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \W.
        /// </summary>
        internal static string NonWord {
            get {
                return ResourceManager.GetString("NonWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \S.
        /// </summary>
        internal static string NotSpace {
            get {
                return ResourceManager.GetString("NotSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \B.
        /// </summary>
        internal static string NotWordBoundary {
            get {
                return ResourceManager.GetString("NotWordBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $n or \n.
        /// </summary>
        internal static string NthReplacement {
            get {
                return ResourceManager.GetString("NthReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \O.
        /// </summary>
        internal static string OctalChar {
            get {
                return ResourceManager.GetString("OctalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \xxx.
        /// </summary>
        internal static string OctalStr {
            get {
                return ResourceManager.GetString("OctalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?&gt;.
        /// </summary>
        internal static string OnceOnly {
            get {
                return ResourceManager.GetString("OnceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [abc].
        /// </summary>
        internal static string OrBracket {
            get {
                return ResourceManager.GetString("OrBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (a|b).
        /// </summary>
        internal static string OrRange {
            get {
                return ResourceManager.GetString("OrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?:...).
        /// </summary>
        internal static string PassiveRange {
            get {
                return ResourceManager.GetString("PassiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string PeriodRange {
            get {
                return ResourceManager.GetString("PeriodRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantifiers.
        /// </summary>
        internal static string Quant {
            get {
                return ResourceManager.GetString("Quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5,7}.
        /// </summary>
        internal static string RangeQuant {
            get {
                return ResourceManager.GetString("RangeQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Replacement.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r.
        /// </summary>
        internal static string ReturnChar {
            get {
                return ResourceManager.GetString("ReturnChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2 or \2.
        /// </summary>
        internal static string SecondReplacement {
            get {
                return ResourceManager.GetString("SecondReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s.
        /// </summary>
        internal static string SpaceChar {
            get {
                return ResourceManager.GetString("SpaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Characters.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A.
        /// </summary>
        internal static string StringBegin {
            get {
                return ResourceManager.GetString("StringBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Z.
        /// </summary>
        internal static string StringEnd {
            get {
                return ResourceManager.GetString("StringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \x.
        /// </summary>
        internal static string SubpatternNum {
            get {
                return ResourceManager.GetString("SubpatternNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \y.
        /// </summary>
        internal static string SubPatternRange {
            get {
                return ResourceManager.GetString("SubPatternRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t.
        /// </summary>
        internal static string TabChar {
            get {
                return ResourceManager.GetString("TabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \v.
        /// </summary>
        internal static string VertTabChar {
            get {
                return ResourceManager.GetString("VertTabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w.
        /// </summary>
        internal static string WordChar {
            get {
                return ResourceManager.GetString("WordChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&gt;.
        /// </summary>
        internal static string WordEnd {
            get {
                return ResourceManager.GetString("WordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&lt;.
        /// </summary>
        internal static string WordStart {
            get {
                return ResourceManager.GetString("WordStart", resourceCulture);
            }
        }
    }
}
