//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegularExpressionsCalculator.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegexLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegexLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegularExpressionsCalculator.App_Data.RegexLinks", typeof(RegexLinks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaretAnchor,^;StringBegin,\A;DollarAnchor,$;StringEnd,\Z;BoundaryAnchor,\b;NotWordBoundary,\B;WordStart,\&lt;;WordEnd,\&gt;.
        /// </summary>
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookahead,?=;NegLookahead,?!;Lookbehind, ?&lt;=;NegLookbehind, ?!= or ?&lt;!;OnceOnly, ?&gt;;IfThen, ?();IfThenElse, ?()|;Comment, ?#.
        /// </summary>
        internal static string Assert {
            get {
                return ResourceManager.GetString("Assert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlChar,\c;SpaceChar,\s;NotSpace,\S;DigitChar,\d;NonDigitChar,\D;WordChar,\w;NonWordChar,\W;HexaChar,\x;OctalChar,\O.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal,\;BeginLiteral,\Q;EndLiteral,\E.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodRange,.;OrRange,(a|b);GroupRange,(...);PassiveRange,(?:...);OrBracket,[abc];NonOrRange,[^abc];BracketRange,[a-e];DigitRange,[0-5];SubPatternRange,\y.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalPattern,\g.
        /// </summary>
        internal static string Mod {
            get {
                return ResourceManager.GetString("Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreedyZero,*;GreedyOne,+;Lazy,?;Exact,{5};AtLeast,{5,};RangeQuant,{5,7}.
        /// </summary>
        internal static string Quant {
            get {
                return ResourceManager.GetString("Quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NthReplacement,$n;SecondReplacement,$2;FirstReplacement,$1;BeforeReplacement,$`;AfterReplace,$&apos;;LastReplacement,$+;EntireReplacement,$&amp;.
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLine,\n;ReturnChar,\r;TabChar,\t;VerTabChar,\v;FeedChar,\f;OctalStr,\xxx;HexStrChar,\xhh.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
    }
}
