//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegularExpressionsCalculator.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegularExpressionsCalculator.App_Data.SampleText", typeof(SampleText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although it is a cold evening, 
        ///down by one of the fishhouses 
        ///an old man sits netting, 
        ///his net, in the gloaming almost invisible, 
        ///a dark purple-brown, 
        ///and his shuttle worn and polished. 
        ///The air smells so strong of codfish 
        ///it makes one’s nose run and one’s eyes water. 
        ///The five fishhouses have steeply peaked roofs 
        ///and narrow, cleated gangplanks slant up 
        ///to storerooms in the gables 
        ///for the wheelbarrows to be pushed up and down on. 
        ///All is silver: the heavy surface of the sea, 
        ///swelling s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtTheFishhouses {
            get {
                return ResourceManager.GetString("AtTheFishhouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You are old, Father William,&quot; the young man said,
        ///&quot;And your hair has become very white;
        ///And yet you incessantly stand on your head—
        ///Do you think, at your age, it is right?&quot;
        ///
        ///&quot;In my youth,&quot; Father William replied to his son,
        ///&quot;I feared it might injure the brain;
        ///But now that I&apos;m perfectly sure I have none,
        ///Why, I do it again and again.&quot;
        ///
        ///&quot;You are old,&quot; said the youth, &quot;As I mentioned before,
        ///And have grown most uncommonly fat;
        ///Yet you turned a back-somersault in at the door—
        ///Pray, what is the re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FatherWilliam {
            get {
                return ResourceManager.GetString("FatherWilliam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A is for Amy who fell down the stairs.
        ///B is for Basil assaulted by bears.
        ///C is for Clair who wasted away.
        ///D is for Desmond thrown out of the sleigh.
        ///E is for Ernest who choked on a peach.
        ///F is for Fanny, sucked dry by a leech.
        ///G is for George, smothered under a rug.
        ///H is for Hector, done in by a thug.
        ///I is for Ida who drowned in the lake.
        ///J is for James who took lye, by mistake.
        ///K is for Kate who was struck with an axe.
        ///L is for Leo who swallowed some tacks.
        ///M is for Maud who was swept out to se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GashlycrumbTinies {
            get {
                return ResourceManager.GetString("GashlycrumbTinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we&apos;re here again, the fat suicide
        ///searching the garbage for a blade of hope,
        ///the worn stairs sighing in the dark,
        ///the bandages unwinding, the black holes
        ///the needles made, the puffed tattoo,
        ///the great belly arguing in its bed.
        ///
        ///We come again and again on our bad feet
        ///or running as the water runs all night
        ///in the old pipes of the Hotel Florida.
        ///She dozes on the bowl, our mother
        ///of Malaga, and sings a little song of home
        ///and washes the city slowly from her thighs.
        ///
        ///All that was desire, all t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ’Twas brillig, and the slithy toves 
        ///      Did gyre and gimble in the wabe: 
        ///All mimsy were the borogoves, 
        ///      And the mome raths outgrabe. 
        ///
        ///“Beware the Jabberwock, my son! 
        ///      The jaws that bite, the claws that catch! 
        ///Beware the Jubjub bird, and shun 
        ///      The frumious Bandersnatch!” 
        ///
        ///He took his vorpal sword in hand; 
        ///      Long time the manxome foe he sought— 
        ///So rested he by the Tumtum tree 
        ///      And stood awhile in thought. 
        ///
        ///And, as in uffish thought he stood, 
        ///      The Jab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jabberwocky {
            get {
                return ResourceManager.GetString("Jabberwocky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have eaten
        ///the plums
        ///that were in
        ///the icebox
        ///
        ///and which
        ///you were probably
        ///saving
        ///for breakfast
        ///
        ///Forgive me
        ///they were delicious
        ///so sweet
        ///and so cold.
        /// </summary>
        internal static string JustToSay {
            get {
                return ResourceManager.GetString("JustToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The art of losing isn’t hard to master; 
        ///so many things seem filled with the intent 
        ///to be lost that their loss is no disaster. 
        ///
        ///Lose something every day. Accept the fluster 
        ///of lost door keys, the hour badly spent. 
        ///The art of losing isn’t hard to master. 
        ///
        ///Then practice losing farther, losing faster: 
        ///places, and names, and where it was you meant 
        ///to travel. None of these will bring disaster. 
        ///
        ///I lost my mother’s watch. And look! my last, or 
        ///next-to-last, of three loved houses went. 
        ///The a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneArt {
            get {
                return ResourceManager.GetString("OneArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of burlap sacks, out of bearing butter, 
        ///Out of black bean and wet slate bread, 
        ///Out of the acids of rage, the candor of tar, 
        ///Out of creosote, gasoline, drive shafts, wooden dollies, 
        ///They Lion grow. 
        ///                        Out of the gray hills 
        ///Of industrial barns, out of rain, out of bus ride, 
        ///West Virginia to Kiss My Ass, out of buried aunties, 
        ///Mothers hardening like pounded stumps, out of stumps, 
        ///Out of the bones’ need to sharpen and the muscles’ to stretch,   
        ///They Lion grow. 
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheyFeedTheyLion {
            get {
                return ResourceManager.GetString("TheyFeedTheyLion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wake to sleep, and take my waking slow.   
        ///I feel my fate in what I cannot fear.   
        ///I learn by going where I have to go. 
        ///
        ///We think by feeling. What is there to know?   
        ///I hear my being dance from ear to ear.   
        ///I wake to sleep, and take my waking slow. 
        ///
        ///Of those so close beside me, which are you?   
        ///God bless the Ground!   I shall walk softly there,   
        ///And learn by going where I have to go. 
        ///
        ///Light takes the Tree; but who can tell us how?   
        ///The lowly worm climbs up a winding stair;   
        ///I w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Waking {
            get {
                return ResourceManager.GetString("Waking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sun was shining on the sea,
        ///Shining with all his might:
        ///He did his very best to make
        ///The billows smooth and bright--
        ///And this was odd, because it was
        ///The middle of the night.
        ///
        ///The moon was shining sulkily,
        ///Because she thought the sun
        ///Had got no business to be there
        ///After the day was done--
        ///&quot;It&apos;s very rude of him,&quot; she said,
        ///&quot;To come and spoil the fun!&quot;
        ///
        ///
        ///The sea was wet as wet could be,
        ///The sands were dry as dry.
        ///You could not see a cloud, because
        ///No cloud was in the sky:
        ///No birds wer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WalrusCarpenter {
            get {
                return ResourceManager.GetString("WalrusCarpenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My brother comes home from work 
        ///and climbs the stairs to our room. 
        ///I can hear the bed groan and his shoes drop   
        ///one by one. You can have it, he says. 
        ///
        ///The moonlight streams in the window   
        ///and his unshaven face is whitened 
        ///like the face of the moon. He will sleep 
        ///long after noon and waken to find me gone. 
        ///
        ///Thirty years will pass before I remember   
        ///that moment when suddenly I knew each man   
        ///has one brother who dies when he sleeps   
        ///and sleeps when he rises to face this life, 
        ///
        ///an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YouCanHaveIt {
            get {
                return ResourceManager.GetString("YouCanHaveIt", resourceCulture);
            }
        }
    }
}
