//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegularExpressionsCalculator.App_Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Symbols {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Symbols() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegularExpressionsCalculator.App_Data.Symbols", typeof(Symbols).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&apos;.
        /// </summary>
        public static string AfterReplace {
            get {
                return ResourceManager.GetString("AfterReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {,}.
        /// </summary>
        public static string AtLeast {
            get {
                return ResourceManager.GetString("AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \`.
        /// </summary>
        public static string BeforeReplace {
            get {
                return ResourceManager.GetString("BeforeReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Q.
        /// </summary>
        public static string BeginLiteral {
            get {
                return ResourceManager.GetString("BeginLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b.
        /// </summary>
        public static string BoundaryAnchor {
            get {
                return ResourceManager.GetString("BoundaryAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        public static string BracketRange {
            get {
                return ResourceManager.GetString("BracketRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string CaretAnchor {
            get {
                return ResourceManager.GetString("CaretAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?#.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \c.
        /// </summary>
        public static string ControlChar {
            get {
                return ResourceManager.GetString("ControlChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d  .
        /// </summary>
        public static string DigitChar {
            get {
                return ResourceManager.GetString("DigitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string DollarAnchor {
            get {
                return ResourceManager.GetString("DollarAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \E.
        /// </summary>
        public static string EndLiteral {
            get {
                return ResourceManager.GetString("EndLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&amp;.
        /// </summary>
        public static string EntireReplacement {
            get {
                return ResourceManager.GetString("EntireReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {}.
        /// </summary>
        public static string ExactRangeQuant {
            get {
                return ResourceManager.GetString("ExactRangeQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \f.
        /// </summary>
        public static string FeedChar {
            get {
                return ResourceManager.GetString("FeedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \1.
        /// </summary>
        public static string FirstReplacement {
            get {
                return ResourceManager.GetString("FirstReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \g.
        /// </summary>
        public static string GlobalPattern {
            get {
                return ResourceManager.GetString("GlobalPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string GreedyOne {
            get {
                return ResourceManager.GetString("GreedyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string GreedyZero {
            get {
                return ResourceManager.GetString("GreedyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ().
        /// </summary>
        public static string GroupRange {
            get {
                return ResourceManager.GetString("GroupRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \x.
        /// </summary>
        public static string HexStrChar {
            get {
                return ResourceManager.GetString("HexStrChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?().
        /// </summary>
        public static string IfThen {
            get {
                return ResourceManager.GetString("IfThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?().
        /// </summary>
        public static string IfThenElse {
            get {
                return ResourceManager.GetString("IfThenElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \+.
        /// </summary>
        public static string LastReplacement {
            get {
                return ResourceManager.GetString("LastReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string Lazy {
            get {
                return ResourceManager.GetString("Lazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        public static string Literal {
            get {
                return ResourceManager.GetString("Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?=.
        /// </summary>
        public static string Lookahead {
            get {
                return ResourceManager.GetString("Lookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?&lt;=.
        /// </summary>
        public static string Lookbehind {
            get {
                return ResourceManager.GetString("Lookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?!.
        /// </summary>
        public static string NegLookahead {
            get {
                return ResourceManager.GetString("NegLookahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?!=;?&lt;!.
        /// </summary>
        public static string NegLookbehind {
            get {
                return ResourceManager.GetString("NegLookbehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n.
        /// </summary>
        public static string NewLine {
            get {
                return ResourceManager.GetString("NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \D.
        /// </summary>
        public static string NonDigit {
            get {
                return ResourceManager.GetString("NonDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^].
        /// </summary>
        public static string NonOr {
            get {
                return ResourceManager.GetString("NonOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^-].
        /// </summary>
        public static string NonRange {
            get {
                return ResourceManager.GetString("NonRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \W.
        /// </summary>
        public static string NonWord {
            get {
                return ResourceManager.GetString("NonWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \S.
        /// </summary>
        public static string NotSpace {
            get {
                return ResourceManager.GetString("NotSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \B.
        /// </summary>
        public static string NotWordBoundary {
            get {
                return ResourceManager.GetString("NotWordBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $n;\n.
        /// </summary>
        public static string NthReplacement {
            get {
                return ResourceManager.GetString("NthReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \O.
        /// </summary>
        public static string OctalChar {
            get {
                return ResourceManager.GetString("OctalChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?&gt;.
        /// </summary>
        public static string OnceOnly {
            get {
                return ResourceManager.GetString("OnceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        public static string OrBracket {
            get {
                return ResourceManager.GetString("OrBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (|).
        /// </summary>
        public static string OrRange {
            get {
                return ResourceManager.GetString("OrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?:).
        /// </summary>
        public static string PassiveRange {
            get {
                return ResourceManager.GetString("PassiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string PeriodRange {
            get {
                return ResourceManager.GetString("PeriodRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {,}.
        /// </summary>
        public static string RangeQuant {
            get {
                return ResourceManager.GetString("RangeQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r.
        /// </summary>
        public static string ReturnChar {
            get {
                return ResourceManager.GetString("ReturnChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2;\2 .
        /// </summary>
        public static string SecondReplacement {
            get {
                return ResourceManager.GetString("SecondReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s.
        /// </summary>
        public static string SpaceChar {
            get {
                return ResourceManager.GetString("SpaceChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \A.
        /// </summary>
        public static string StringBegin {
            get {
                return ResourceManager.GetString("StringBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Z.
        /// </summary>
        public static string StringEnd {
            get {
                return ResourceManager.GetString("StringEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \x.
        /// </summary>
        public static string SubpatternNum {
            get {
                return ResourceManager.GetString("SubpatternNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \t.
        /// </summary>
        public static string TabChar {
            get {
                return ResourceManager.GetString("TabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \v.
        /// </summary>
        public static string VertTabChar {
            get {
                return ResourceManager.GetString("VertTabChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w.
        /// </summary>
        public static string WordChar {
            get {
                return ResourceManager.GetString("WordChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&gt;.
        /// </summary>
        public static string WordEnd {
            get {
                return ResourceManager.GetString("WordEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&lt;.
        /// </summary>
        public static string WordStart {
            get {
                return ResourceManager.GetString("WordStart", resourceCulture);
            }
        }
    }
}
